import Wine1 from "./assets/wine1.png";
import Wine2 from "./assets/wine2.png";
import Wine3 from "./assets/wine3.png";
import Wine4 from "./assets/wine4.png";
import Wine5 from "./assets/wine5.png";
import Wine6 from "./assets/wine6.png";
import Wine7 from "./assets/wine7.png";
import Wine8 from "./assets/wine8.png";
import Wine9 from "./assets/wine9.png";
import Wine10 from "./assets/wine10.png";
import Wine11 from "./assets/wine11.png";
import Wine12 from "./assets/wine12.png";
import Wine13 from "./assets/wine13.png";
import Wine14 from "./assets/wine14.png";
import Wine15 from "./assets/wine15.png";
import Wine16 from "./assets/wine16.png";
import Wine17 from "./assets/wine17.png";
import Wine18 from "./assets/wine18.png";
import Wine19 from "./assets/wine19.png";
import Wine20 from "./assets/wine20.png";
import Wine21 from "./assets/wine21.png";

export const wines = [
    {
      id: 1,
      type: "Red",
      title: "Vintner’s Reserve Cabernet Sauvignon",
      subtitle: "2018 | McLaren Vale",
      volume: "750ml",
      price: "$42",
      memberOnly: true,
      image: Wine1,
      points: 93,
    },
    {
      id: 2,
      type: "Rose",
      title: "Russian River Valley Sparkling Rosé",
      subtitle: "2019 | California",
      volume: "750ml",
      price: "$48",
      memberOnly: false,
      image: Wine2,
      points: 94,
    },
    {
      id: 3,
      type: "White",
      title: "Estate Chardonnay",
      subtitle: "2020 | Napa Valley",
      volume: "750ml",
      price: "$38",
      memberOnly: true,
      image: Wine3,
      points: 92,
    },
    {
      id: 4,
      type: "Sparkling",
      title: "California 2010 Exquisite",
      subtitle: "2020 | Napa Valley",
      volume: "750ml",
      price: "$50",
      memberOnly: false,
      image: Wine4,
      points: 92,
    },
    {
      id: 5,
      type: "Red",
      title: "Blanc de Blanc",
      subtitle: "2014 | Paris",
      volume: "750ml",
      price: "$33",
      memberOnly: true,
      image: Wine5,
      points: 96,
    },
    {
      id: 6,
      type: "Rose",
      title: "Riviera",
      subtitle: "2014 | Lyon da Falle",
      volume: "750ml",
      price: "$40",
      memberOnly: false,
      image: Wine6,
      points: 94,
    },
    {
      id: 7,
      type: "Red",
      title: "Rusina",
      subtitle: "2017 | Lyon da Falle",
      volume: "850ml",
      price: "$42",
      memberOnly: false,
      image: Wine7,
      points: 94,
    },
     {
      id: 8,
      type: "Red",
      title: "Plie",
      subtitle: "2009 | sacre da Fal",
      volume: "800ml",
      price: "$41",
      memberOnly: true,
      image: Wine8,
      points: 88,
    },
    {
      id: 9,
      type: "White",
      title: "sara mange",
      subtitle: "1995 | Los Angeles",
      volume: "800ml",
      price: "$34",
      memberOnly: true,
      image: Wine9,
      points: 79,
    },
     {
      id: 10,
      type: "Sparkling",
      title: "reage",
      subtitle: "2017 | Nice",
      volume: "850ml",
      price: "$46",
      memberOnly: true,
      image: Wine10,
      points: 80,
    },
    {
      id: 11,
      type: "White",
      title: "Shea",
      subtitle: "2010 | da Falle",
      volume: "850ml",
      price: "$44",
      memberOnly: false,
      image: Wine11,
      points: 71,
    },
    {
      id: 12,
      type: "White",
      title: "Blanche",
      subtitle: "2020 | Mumbai",
      volume: "850ml",
      price: "$42",
      memberOnly: false,
      image: Wine12,
      points: 94,
    },
        {
      id: 13,
      type: "Rose",
      title: "Ralle",
      subtitle: "2004| Muscat",
      volume: "850ml",
      price: "$60",
      memberOnly: false,
      image: Wine13,
      points: 94,
    },
    {
      id: 14,
      type: "Rose",
      title: "Russchia",
      subtitle: "2017 | Russia",
      volume: "850ml",
      price: "$42",
      memberOnly: false,
      image: Wine14,
      points: 94,
    },
    {
      id: 15,
      type: "White",
      title: "Rebecca",
      subtitle: "2017 | France",
      volume: "850ml",
      price: "$42",
      memberOnly: false,
      image: Wine15,
      points: 94,
    },
    {
      id: 16,
      type: "Red",
      title: "Rusina",
      subtitle: "2017 | Lyon da Falle",
      volume: "850ml",
      price: "$42",
      memberOnly: false,
      image: Wine16,
      points: 94,
    },
    {
      id: 17,
      type: "Sparkling",
      title: "Meteor",
      subtitle: "2003 | Arizona",
      volume: "850ml",
      price: "$49",
      memberOnly: true,
      image: Wine17,
      points: 94,
    },
    {
      id: 18,
      type: "Sparkling",
      title: "Amy",
      subtitle: "2017 | Las Vegas",
      volume: "850ml",
      price: "$33",
      memberOnly: false,
      image: Wine18,
      points: 94,
    },
        {
      id: 19,
      type: "Red",
      title: "Ameen",
      subtitle: "2007 | Iran",
      volume: "900ml",
      price: "$42",
      memberOnly: false,
      image: Wine19,
      points: 94,
    },
    {
      id: 20,
      type: "Sparkling",
      title: "Begum",
      subtitle: "1997 | Oman",
      volume: "850ml",
      price: "$39",
      memberOnly: false,
      image: Wine20,
      points: 94,
    },
    {
      id: 21,
      type: "Rose",
      title: "Shariqa",
      subtitle: "2017 | Bahrain",
      volume: "850ml",
      price: "$55",
      memberOnly: false,
      image: Wine21,
      points: 94,
    },
];